
name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build debug APK
      run: bash ./gradlew app:bundleRelease --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
          name: app
          path: app/release/app-release.aab

    - name: Create service_account.json
      run: echo '${{ secrets.ACCOUNT_SECRET }}' > service_account.json
    - name: Deploy to Play Store internal
      uses: r0adkll/upload-google-play@v1.0.15
      with:
        serviceAccountJson: service_account.json
        packageName: com.vitt.actions.actions
        releaseFiles: app/release/*.aab
        track: beta
        mappingFile: app/build/outputs/mapping/release/mapping.txt
        inAppUpdatePriority: 5
