
name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build debug APK
      run: bash ./gradlew assembleDebug --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

    - name: Create service_account.json
      run: echo '${{ secrets.ACCOUNT_SECRET }}' > service_account.json
    - name: Deploy to Play Store
      uses: r0adkll/upload-google-play@v1.0.15
      with:
        serviceAccountJson: service_account.json
        packageName: ${{ github.event.inputs.app_id }}
        releaseFiles: app/build/outputs/bundle/release/*.aab
        track: internal
        whatsNewDirectory: whatsnew/
        mappingFile: app/build/outputs/mapping/release/mapping.txt
        inAppUpdatePriority: 5
